# Generated by Django 3.0.5 on 2020-05-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200505_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='authkeymodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
